import { Montserrat} from "next/font/google";
import "./globals.css";
import Loginpage from "@/components/Logincomponents/Loginpage";
import NextuiProviderWrapper from "./NextUIProvider";
import {Providers} from "../lib/provider"

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>

    <html lang="en">
      <body className={inter.className}>
      <NextuiProviderWrapper>
          {children}
        </NextuiProviderWrapper>
      </body>
    </html>
    </Providers>
  );
}
